### ISSUE TITLE
宽度自适应与隐藏图片按钮的问题

### ISSUE THREAD

**Issue by eryajf** [terwer/vuepress-plugin-vdoing-comment#2]
## 问题一

图片按钮隐藏目前使用README里提供的参数项配置没有效果，这里给了一个方案：https://github.com/ArtalkJS/Artalk/issues/313#issuecomment-1328073405 ，目前用下来可行。我想是不是也可以集成到这个插件里来。

## 问题二

评论区宽度自适应的问题，如下截图：

<img width="887" alt="image" src="https://user-images.githubusercontent.com/33259379/204128870-3890c929-3cce-47ad-a4be-b10d475eb749.png">

当页面宽度变窄的时候，评论区的宽度没有与内容区对齐。

**Comment by terwer** [comment]
1.0.4已解决问题一。

**Comment by terwer** [comment]
1.0.5已解决问题二。
