### ISSUE TITLE
artalk来到了 2.6.2 版本

### ISSUE THREAD

**Issue by eryajf** [terwer/vuepress-plugin-vdoing-comment#7]
如题。

**Comment by eryajf** [comment]
我升级了后端，现在每篇都先是这个提示😂

![image_20230929_103912](https://cdn.jsdelivr.net/gh/eryajf/tu@main/img/image_20230929_103912.png)

**Comment by terwer** [comment]
`1.2.0` 我升级到了 `2.8.3` 看看还有问题没。

**Comment by terwer** [comment]
`1.3.0` 我升级到了 `2.8.7 ` 。
